import Header from '@/components/header/header'
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

import "/sass/bootstrap.scss";
import '/sass/style.scss';
import BootstrapClient from "@/components/bootstrapClient";

export const metadata = {
  title: "Clemo - Portfolio Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <BootstrapClient />
        {children}
      </body>
    </html>
  );
}
